# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_git_repo_volume_source import IoFabric8KubernetesApiModelGitRepoVolumeSource  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelGitRepoVolumeSource(unittest.TestCase):
    """IoFabric8KubernetesApiModelGitRepoVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelGitRepoVolumeSource(self):
        """Test IoFabric8KubernetesApiModelGitRepoVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_git_repo_volume_source.IoFabric8KubernetesApiModelGitRepoVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
