# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_pod_resource_claim import IoFabric8KubernetesApiModelPodResourceClaim  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelPodResourceClaim(unittest.TestCase):
    """IoFabric8KubernetesApiModelPodResourceClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelPodResourceClaim(self):
        """Test IoFabric8KubernetesApiModelPodResourceClaim"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_pod_resource_claim.IoFabric8KubernetesApiModelPodResourceClaim()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
