# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_artifacts_promotion_workflow import ComCapillaryOpsCpBoArtifactsPromotionWorkflow  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoArtifactsPromotionWorkflow(unittest.TestCase):
    """ComCapillaryOpsCpBoArtifactsPromotionWorkflow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoArtifactsPromotionWorkflow(self):
        """Test ComCapillaryOpsCpBoArtifactsPromotionWorkflow"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_artifacts_promotion_workflow.ComCapillaryOpsCpBoArtifactsPromotionWorkflow()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
