# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_deployer_bo_health_check import ComCapillaryOpsDeployerBoHealthCheck  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsDeployerBoHealthCheck(unittest.TestCase):
    """ComCapillaryOpsDeployerBoHealthCheck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsDeployerBoHealthCheck(self):
        """Test ComCapillaryOpsDeployerBoHealthCheck"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_deployer_bo_health_check.ComCapillaryOpsDeployerBoHealthCheck()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
