# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_deployment_status_count_dto import ComCapillaryOpsCpBoDeploymentStatusCountDto  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoDeploymentStatusCountDto(unittest.TestCase):
    """ComCapillaryOpsCpBoDeploymentStatusCountDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoDeploymentStatusCountDto(self):
        """Test ComCapillaryOpsCpBoDeploymentStatusCountDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_deployment_status_count_dto.ComCapillaryOpsCpBoDeploymentStatusCountDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
