# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_v2_assistants_bo_assistant import ComCapillaryOpsCpV2AssistantsBoAssistant  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpV2AssistantsBoAssistant(unittest.TestCase):
    """ComCapillaryOpsCpV2AssistantsBoAssistant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpV2AssistantsBoAssistant(self):
        """Test ComCapillaryOpsCpV2AssistantsBoAssistant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_v2_assistants_bo_assistant.ComCapillaryOpsCpV2AssistantsBoAssistant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
