# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_history_deleted_entity_com_capillary_ops_cp_bo_history_soft_delete import ComCapillaryOpsCpBoHistoryDeletedEntityComCapillaryOpsCpBoHistorySoftDelete  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoHistoryDeletedEntityComCapillaryOpsCpBoHistorySoftDelete(unittest.TestCase):
    """ComCapillaryOpsCpBoHistoryDeletedEntityComCapillaryOpsCpBoHistorySoftDelete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoHistoryDeletedEntityComCapillaryOpsCpBoHistorySoftDelete(self):
        """Test ComCapillaryOpsCpBoHistoryDeletedEntityComCapillaryOpsCpBoHistorySoftDelete"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_history_deleted_entity_com_capillary_ops_cp_bo_history_soft_delete.ComCapillaryOpsCpBoHistoryDeletedEntityComCapillaryOpsCpBoHistorySoftDelete()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
