# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_host_alias import IoFabric8KubernetesApiModelHostAlias  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelHostAlias(unittest.TestCase):
    """IoFabric8KubernetesApiModelHostAlias unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelHostAlias(self):
        """Test IoFabric8KubernetesApiModelHostAlias"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_host_alias.IoFabric8KubernetesApiModelHostAlias()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
