# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_json_json_object import OrgJsonJSONObject  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgJsonJSONObject(unittest.TestCase):
    """OrgJsonJSONObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgJsonJSONObject(self):
        """Test OrgJsonJSONObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_json_json_object.OrgJsonJSONObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
