# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_artifacts_artifact_routing_rule_response import ComCapillaryOpsCpBoArtifactsArtifactRoutingRuleResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoArtifactsArtifactRoutingRuleResponse(unittest.TestCase):
    """ComCapillaryOpsCpBoArtifactsArtifactRoutingRuleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoArtifactsArtifactRoutingRuleResponse(self):
        """Test ComCapillaryOpsCpBoArtifactsArtifactRoutingRuleResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_artifacts_artifact_routing_rule_response.ComCapillaryOpsCpBoArtifactsArtifactRoutingRuleResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
