# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_object_meta import IoFabric8KubernetesApiModelObjectMeta  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelObjectMeta(unittest.TestCase):
    """IoFabric8KubernetesApiModelObjectMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelObjectMeta(self):
        """Test IoFabric8KubernetesApiModelObjectMeta"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_object_meta.IoFabric8KubernetesApiModelObjectMeta()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
