# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_v2_resourcesync_bo_release_preview_response import ComCapillaryOpsCpV2ResourcesyncBoReleasePreviewResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpV2ResourcesyncBoReleasePreviewResponse(unittest.TestCase):
    """ComCapillaryOpsCpV2ResourcesyncBoReleasePreviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpV2ResourcesyncBoReleasePreviewResponse(self):
        """Test ComCapillaryOpsCpV2ResourcesyncBoReleasePreviewResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_v2_resourcesync_bo_release_preview_response.ComCapillaryOpsCpV2ResourcesyncBoReleasePreviewResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
