# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_springframework_data_domain_page_com_capillary_ops_cp_bo_audit_facets_audit_log_response import OrgSpringframeworkDataDomainPageComCapillaryOpsCpBoAuditFacetsAuditLogResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgSpringframeworkDataDomainPageComCapillaryOpsCpBoAuditFacetsAuditLogResponse(unittest.TestCase):
    """OrgSpringframeworkDataDomainPageComCapillaryOpsCpBoAuditFacetsAuditLogResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgSpringframeworkDataDomainPageComCapillaryOpsCpBoAuditFacetsAuditLogResponse(self):
        """Test OrgSpringframeworkDataDomainPageComCapillaryOpsCpBoAuditFacetsAuditLogResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_springframework_data_domain_page_com_capillary_ops_cp_bo_audit_facets_audit_log_response.OrgSpringframeworkDataDomainPageComCapillaryOpsCpBoAuditFacetsAuditLogResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
