# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_k8s_dto_secret_dto import ComCapillaryOpsCpBoK8sDtoSecretDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoK8sDtoSecretDTO(unittest.TestCase):
    """ComCapillaryOpsCpBoK8sDtoSecretDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoK8sDtoSecretDTO(self):
        """Test ComCapillaryOpsCpBoK8sDtoSecretDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_k8s_dto_secret_dto.ComCapillaryOpsCpBoK8sDtoSecretDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
