# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_springframework_web_servlet_mvc_method_annotation_streaming_response_body import OrgSpringframeworkWebServletMvcMethodAnnotationStreamingResponseBody  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgSpringframeworkWebServletMvcMethodAnnotationStreamingResponseBody(unittest.TestCase):
    """OrgSpringframeworkWebServletMvcMethodAnnotationStreamingResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgSpringframeworkWebServletMvcMethodAnnotationStreamingResponseBody(self):
        """Test OrgSpringframeworkWebServletMvcMethodAnnotationStreamingResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_springframework_web_servlet_mvc_method_annotation_streaming_response_body.OrgSpringframeworkWebServletMvcMethodAnnotationStreamingResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
