# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_autoscaling_v2_metric_identifier import IoFabric8KubernetesApiModelAutoscalingV2MetricIdentifier  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelAutoscalingV2MetricIdentifier(unittest.TestCase):
    """IoFabric8KubernetesApiModelAutoscalingV2MetricIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelAutoscalingV2MetricIdentifier(self):
        """Test IoFabric8KubernetesApiModelAutoscalingV2MetricIdentifier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_autoscaling_v2_metric_identifier.IoFabric8KubernetesApiModelAutoscalingV2MetricIdentifier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
