# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_requests_designer_resource_file_request import ComCapillaryOpsCpBoRequestsDesignerResourceFileRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoRequestsDesignerResourceFileRequest(unittest.TestCase):
    """ComCapillaryOpsCpBoRequestsDesignerResourceFileRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoRequestsDesignerResourceFileRequest(self):
        """Test ComCapillaryOpsCpBoRequestsDesignerResourceFileRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_requests_designer_resource_file_request.ComCapillaryOpsCpBoRequestsDesignerResourceFileRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
