# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_v2_projecttype_bo_project_type_mapped_resource import ComCapillaryOpsCpV2ProjecttypeBoProjectTypeMappedResource  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpV2ProjecttypeBoProjectTypeMappedResource(unittest.TestCase):
    """ComCapillaryOpsCpV2ProjecttypeBoProjectTypeMappedResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpV2ProjecttypeBoProjectTypeMappedResource(self):
        """Test ComCapillaryOpsCpV2ProjecttypeBoProjectTypeMappedResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_v2_projecttype_bo_project_type_mapped_resource.ComCapillaryOpsCpV2ProjecttypeBoProjectTypeMappedResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
