# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_fields_v1 import IoFabric8KubernetesApiModelFieldsV1  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelFieldsV1(unittest.TestCase):
    """IoFabric8KubernetesApiModelFieldsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelFieldsV1(self):
        """Test IoFabric8KubernetesApiModelFieldsV1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_fields_v1.IoFabric8KubernetesApiModelFieldsV1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
