# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_deployer_bo_application_metrics_wrapper import ComCapillaryOpsDeployerBoApplicationMetricsWrapper  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsDeployerBoApplicationMetricsWrapper(unittest.TestCase):
    """ComCapillaryOpsDeployerBoApplicationMetricsWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsDeployerBoApplicationMetricsWrapper(self):
        """Test ComCapillaryOpsDeployerBoApplicationMetricsWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_deployer_bo_application_metrics_wrapper.ComCapillaryOpsDeployerBoApplicationMetricsWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
