# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_label_selector import IoFabric8KubernetesApiModelLabelSelector  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelLabelSelector(unittest.TestCase):
    """IoFabric8KubernetesApiModelLabelSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelLabelSelector(self):
        """Test IoFabric8KubernetesApiModelLabelSelector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_label_selector.IoFabric8KubernetesApiModelLabelSelector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
