# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_k8s_dto_cron_job_dto import ComCapillaryOpsCpBoK8sDtoCronJobDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoK8sDtoCronJobDTO(unittest.TestCase):
    """ComCapillaryOpsCpBoK8sDtoCronJobDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoK8sDtoCronJobDTO(self):
        """Test ComCapillaryOpsCpBoK8sDtoCronJobDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_k8s_dto_cron_job_dto.ComCapillaryOpsCpBoK8sDtoCronJobDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
