# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_toleration import IoFabric8KubernetesApiModelToleration  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelToleration(unittest.TestCase):
    """IoFabric8KubernetesApiModelToleration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelToleration(self):
        """Test IoFabric8KubernetesApiModelToleration"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_toleration.IoFabric8KubernetesApiModelToleration()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
