# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_seccomp_profile import IoFabric8KubernetesApiModelSeccompProfile  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelSeccompProfile(unittest.TestCase):
    """IoFabric8KubernetesApiModelSeccompProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelSeccompProfile(self):
        """Test IoFabric8KubernetesApiModelSeccompProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_seccomp_profile.IoFabric8KubernetesApiModelSeccompProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
