# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_container_state_waiting import IoFabric8KubernetesApiModelContainerStateWaiting  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelContainerStateWaiting(unittest.TestCase):
    """IoFabric8KubernetesApiModelContainerStateWaiting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelContainerStateWaiting(self):
        """Test IoFabric8KubernetesApiModelContainerStateWaiting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_container_state_waiting.IoFabric8KubernetesApiModelContainerStateWaiting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
