# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_resouces_resource_affected_response_target_resource import ComCapillaryOpsCpBoResoucesResourceAffectedResponseTargetResource  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoResoucesResourceAffectedResponseTargetResource(unittest.TestCase):
    """ComCapillaryOpsCpBoResoucesResourceAffectedResponseTargetResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoResoucesResourceAffectedResponseTargetResource(self):
        """Test ComCapillaryOpsCpBoResoucesResourceAffectedResponseTargetResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_resouces_resource_affected_response_target_resource.ComCapillaryOpsCpBoResoucesResourceAffectedResponseTargetResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
