# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_int_or_string import IoFabric8KubernetesApiModelIntOrString  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelIntOrString(unittest.TestCase):
    """IoFabric8KubernetesApiModelIntOrString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelIntOrString(self):
        """Test IoFabric8KubernetesApiModelIntOrString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_int_or_string.IoFabric8KubernetesApiModelIntOrString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
