# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_v2_maintenancewindow_bo_maintenance_window_dto import ComCapillaryOpsCpV2MaintenancewindowBoMaintenanceWindowDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpV2MaintenancewindowBoMaintenanceWindowDTO(unittest.TestCase):
    """ComCapillaryOpsCpV2MaintenancewindowBoMaintenanceWindowDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpV2MaintenancewindowBoMaintenanceWindowDTO(self):
        """Test ComCapillaryOpsCpV2MaintenancewindowBoMaintenanceWindowDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_v2_maintenancewindow_bo_maintenance_window_dto.ComCapillaryOpsCpV2MaintenancewindowBoMaintenanceWindowDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
