# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.org_springframework_security_oauth2_core_client_authentication_method import OrgSpringframeworkSecurityOauth2CoreClientAuthenticationMethod  # noqa: E501
from swagger_client.rest import ApiException


class TestOrgSpringframeworkSecurityOauth2CoreClientAuthenticationMethod(unittest.TestCase):
    """OrgSpringframeworkSecurityOauth2CoreClientAuthenticationMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgSpringframeworkSecurityOauth2CoreClientAuthenticationMethod(self):
        """Test OrgSpringframeworkSecurityOauth2CoreClientAuthenticationMethod"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.org_springframework_security_oauth2_core_client_authentication_method.OrgSpringframeworkSecurityOauth2CoreClientAuthenticationMethod()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
