# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_ephemeral_container import IoFabric8KubernetesApiModelEphemeralContainer  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelEphemeralContainer(unittest.TestCase):
    """IoFabric8KubernetesApiModelEphemeralContainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelEphemeralContainer(self):
        """Test IoFabric8KubernetesApiModelEphemeralContainer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_ephemeral_container.IoFabric8KubernetesApiModelEphemeralContainer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
