# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_config_map_key_selector import IoFabric8KubernetesApiModelConfigMapKeySelector  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelConfigMapKeySelector(unittest.TestCase):
    """IoFabric8KubernetesApiModelConfigMapKeySelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelConfigMapKeySelector(self):
        """Test IoFabric8KubernetesApiModelConfigMapKeySelector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_config_map_key_selector.IoFabric8KubernetesApiModelConfigMapKeySelector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
