# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_requests_customer_onboard_request import ComCapillaryOpsCpBoRequestsCustomerOnboardRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoRequestsCustomerOnboardRequest(unittest.TestCase):
    """ComCapillaryOpsCpBoRequestsCustomerOnboardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoRequestsCustomerOnboardRequest(self):
        """Test ComCapillaryOpsCpBoRequestsCustomerOnboardRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_requests_customer_onboard_request.ComCapillaryOpsCpBoRequestsCustomerOnboardRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
