# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_wrappers_deployment_overview_execution_time import ComCapillaryOpsCpBoWrappersDeploymentOverviewExecutionTime  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoWrappersDeploymentOverviewExecutionTime(unittest.TestCase):
    """ComCapillaryOpsCpBoWrappersDeploymentOverviewExecutionTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoWrappersDeploymentOverviewExecutionTime(self):
        """Test ComCapillaryOpsCpBoWrappersDeploymentOverviewExecutionTime"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_wrappers_deployment_overview_execution_time.ComCapillaryOpsCpBoWrappersDeploymentOverviewExecutionTime()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
