# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.io_fabric8_kubernetes_api_model_persistent_volume_claim_template import IoFabric8KubernetesApiModelPersistentVolumeClaimTemplate  # noqa: E501
from swagger_client.rest import ApiException


class TestIoFabric8KubernetesApiModelPersistentVolumeClaimTemplate(unittest.TestCase):
    """IoFabric8KubernetesApiModelPersistentVolumeClaimTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoFabric8KubernetesApiModelPersistentVolumeClaimTemplate(self):
        """Test IoFabric8KubernetesApiModelPersistentVolumeClaimTemplate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_fabric8_kubernetes_api_model_persistent_volume_claim_template.IoFabric8KubernetesApiModelPersistentVolumeClaimTemplate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
