# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.com_capillary_ops_cp_bo_accounts_versioncontrol_gitlab_gitlab_oauth_app_payload import ComCapillaryOpsCpBoAccountsVersioncontrolGitlabGitlabOauthAppPayload  # noqa: E501
from swagger_client.rest import ApiException


class TestComCapillaryOpsCpBoAccountsVersioncontrolGitlabGitlabOauthAppPayload(unittest.TestCase):
    """ComCapillaryOpsCpBoAccountsVersioncontrolGitlabGitlabOauthAppPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComCapillaryOpsCpBoAccountsVersioncontrolGitlabGitlabOauthAppPayload(self):
        """Test ComCapillaryOpsCpBoAccountsVersioncontrolGitlabGitlabOauthAppPayload"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.com_capillary_ops_cp_bo_accounts_versioncontrol_gitlab_gitlab_oauth_app_payload.ComCapillaryOpsCpBoAccountsVersioncontrolGitlabGitlabOauthAppPayload()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
