# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoDeployment(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'application_family': 'str',
        'application_id': 'str',
        'build_id': 'str',
        'environment': 'str',
        'configurations': 'list[ComCapillaryOpsDeployerBoEnvironmentVariable]',
        'timestamp': 'datetime',
        'pod_size': 'str',
        'horizontal_pod_autoscaler': 'ComCapillaryOpsDeployerBoHPA',
        'schedule': 'str',
        'rollback_enabled': 'bool',
        'deployed_by': 'str',
        'replicas': 'int',
        'configurations_map': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'id',
        'application_family': 'applicationFamily',
        'application_id': 'applicationId',
        'build_id': 'buildId',
        'environment': 'environment',
        'configurations': 'configurations',
        'timestamp': 'timestamp',
        'pod_size': 'podSize',
        'horizontal_pod_autoscaler': 'horizontalPodAutoscaler',
        'schedule': 'schedule',
        'rollback_enabled': 'rollbackEnabled',
        'deployed_by': 'deployedBy',
        'replicas': 'replicas',
        'configurations_map': 'configurationsMap'
    }

    def __init__(self, id=None, application_family=None, application_id=None, build_id=None, environment=None, configurations=None, timestamp=None, pod_size=None, horizontal_pod_autoscaler=None, schedule=None, rollback_enabled=None, deployed_by=None, replicas=None, configurations_map=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoDeployment - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._application_family = None
        self._application_id = None
        self._build_id = None
        self._environment = None
        self._configurations = None
        self._timestamp = None
        self._pod_size = None
        self._horizontal_pod_autoscaler = None
        self._schedule = None
        self._rollback_enabled = None
        self._deployed_by = None
        self._replicas = None
        self._configurations_map = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if application_family is not None:
            self.application_family = application_family
        if application_id is not None:
            self.application_id = application_id
        if build_id is not None:
            self.build_id = build_id
        if environment is not None:
            self.environment = environment
        if configurations is not None:
            self.configurations = configurations
        if timestamp is not None:
            self.timestamp = timestamp
        if pod_size is not None:
            self.pod_size = pod_size
        if horizontal_pod_autoscaler is not None:
            self.horizontal_pod_autoscaler = horizontal_pod_autoscaler
        if schedule is not None:
            self.schedule = schedule
        if rollback_enabled is not None:
            self.rollback_enabled = rollback_enabled
        if deployed_by is not None:
            self.deployed_by = deployed_by
        if replicas is not None:
            self.replicas = replicas
        if configurations_map is not None:
            self.configurations_map = configurations_map

    @property
    def id(self):
        """Gets the id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComCapillaryOpsDeployerBoDeployment.


        :param id: The id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def application_family(self):
        """Gets the application_family of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The application_family of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._application_family

    @application_family.setter
    def application_family(self, application_family):
        """Sets the application_family of this ComCapillaryOpsDeployerBoDeployment.


        :param application_family: The application_family of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """
        allowed_values = ["CRM", "ECOMMERCE", "INTEGRATIONS", "OPS"]  # noqa: E501
        if application_family not in allowed_values:
            raise ValueError(
                "Invalid value for `application_family` ({0}), must be one of {1}"  # noqa: E501
                .format(application_family, allowed_values)
            )

        self._application_family = application_family

    @property
    def application_id(self):
        """Gets the application_id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The application_id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this ComCapillaryOpsDeployerBoDeployment.


        :param application_id: The application_id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def build_id(self):
        """Gets the build_id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The build_id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._build_id

    @build_id.setter
    def build_id(self, build_id):
        """Sets the build_id of this ComCapillaryOpsDeployerBoDeployment.


        :param build_id: The build_id of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """

        self._build_id = build_id

    @property
    def environment(self):
        """Gets the environment of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The environment of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._environment

    @environment.setter
    def environment(self, environment):
        """Sets the environment of this ComCapillaryOpsDeployerBoDeployment.


        :param environment: The environment of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """

        self._environment = environment

    @property
    def configurations(self):
        """Gets the configurations of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The configurations of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: list[ComCapillaryOpsDeployerBoEnvironmentVariable]
        """
        return self._configurations

    @configurations.setter
    def configurations(self, configurations):
        """Sets the configurations of this ComCapillaryOpsDeployerBoDeployment.


        :param configurations: The configurations of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: list[ComCapillaryOpsDeployerBoEnvironmentVariable]
        """

        self._configurations = configurations

    @property
    def timestamp(self):
        """Gets the timestamp of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The timestamp of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ComCapillaryOpsDeployerBoDeployment.


        :param timestamp: The timestamp of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: datetime
        """

        self._timestamp = timestamp

    @property
    def pod_size(self):
        """Gets the pod_size of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The pod_size of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._pod_size

    @pod_size.setter
    def pod_size(self, pod_size):
        """Sets the pod_size of this ComCapillaryOpsDeployerBoDeployment.


        :param pod_size: The pod_size of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """
        allowed_values = ["SMALL", "LARGE", "XLARGE", "XXLARGE", "TINY", "MICRO"]  # noqa: E501
        if pod_size not in allowed_values:
            raise ValueError(
                "Invalid value for `pod_size` ({0}), must be one of {1}"  # noqa: E501
                .format(pod_size, allowed_values)
            )

        self._pod_size = pod_size

    @property
    def horizontal_pod_autoscaler(self):
        """Gets the horizontal_pod_autoscaler of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The horizontal_pod_autoscaler of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: ComCapillaryOpsDeployerBoHPA
        """
        return self._horizontal_pod_autoscaler

    @horizontal_pod_autoscaler.setter
    def horizontal_pod_autoscaler(self, horizontal_pod_autoscaler):
        """Sets the horizontal_pod_autoscaler of this ComCapillaryOpsDeployerBoDeployment.


        :param horizontal_pod_autoscaler: The horizontal_pod_autoscaler of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: ComCapillaryOpsDeployerBoHPA
        """

        self._horizontal_pod_autoscaler = horizontal_pod_autoscaler

    @property
    def schedule(self):
        """Gets the schedule of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The schedule of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._schedule

    @schedule.setter
    def schedule(self, schedule):
        """Sets the schedule of this ComCapillaryOpsDeployerBoDeployment.


        :param schedule: The schedule of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """

        self._schedule = schedule

    @property
    def rollback_enabled(self):
        """Gets the rollback_enabled of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The rollback_enabled of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: bool
        """
        return self._rollback_enabled

    @rollback_enabled.setter
    def rollback_enabled(self, rollback_enabled):
        """Sets the rollback_enabled of this ComCapillaryOpsDeployerBoDeployment.


        :param rollback_enabled: The rollback_enabled of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: bool
        """

        self._rollback_enabled = rollback_enabled

    @property
    def deployed_by(self):
        """Gets the deployed_by of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The deployed_by of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: str
        """
        return self._deployed_by

    @deployed_by.setter
    def deployed_by(self, deployed_by):
        """Sets the deployed_by of this ComCapillaryOpsDeployerBoDeployment.


        :param deployed_by: The deployed_by of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: str
        """

        self._deployed_by = deployed_by

    @property
    def replicas(self):
        """Gets the replicas of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The replicas of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: int
        """
        return self._replicas

    @replicas.setter
    def replicas(self, replicas):
        """Sets the replicas of this ComCapillaryOpsDeployerBoDeployment.


        :param replicas: The replicas of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: int
        """

        self._replicas = replicas

    @property
    def configurations_map(self):
        """Gets the configurations_map of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501


        :return: The configurations_map of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._configurations_map

    @configurations_map.setter
    def configurations_map(self, configurations_map):
        """Sets the configurations_map of this ComCapillaryOpsDeployerBoDeployment.


        :param configurations_map: The configurations_map of this ComCapillaryOpsDeployerBoDeployment.  # noqa: E501
        :type: dict(str, str)
        """

        self._configurations_map = configurations_map

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoDeployment, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoDeployment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
