# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoECRRegistry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'uri': 'str',
        'aws_key': 'str',
        'aws_secret': 'str',
        'aws_region': 'str',
        'aws_account_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'uri': 'uri',
        'aws_key': 'awsKey',
        'aws_secret': 'awsSecret',
        'aws_region': 'awsRegion',
        'aws_account_id': 'awsAccountId'
    }

    def __init__(self, id=None, name=None, uri=None, aws_key=None, aws_secret=None, aws_region=None, aws_account_id=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoECRRegistry - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._uri = None
        self._aws_key = None
        self._aws_secret = None
        self._aws_region = None
        self._aws_account_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        self.name = name
        if uri is not None:
            self.uri = uri
        self.aws_key = aws_key
        self.aws_secret = aws_secret
        self.aws_region = aws_region
        self.aws_account_id = aws_account_id

    @property
    def id(self):
        """Gets the id of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The id of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComCapillaryOpsDeployerBoECRRegistry.


        :param id: The id of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The name of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ComCapillaryOpsDeployerBoECRRegistry.


        :param name: The name of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def uri(self):
        """Gets the uri of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The uri of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """Sets the uri of this ComCapillaryOpsDeployerBoECRRegistry.


        :param uri: The uri of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """

        self._uri = uri

    @property
    def aws_key(self):
        """Gets the aws_key of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The aws_key of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._aws_key

    @aws_key.setter
    def aws_key(self, aws_key):
        """Sets the aws_key of this ComCapillaryOpsDeployerBoECRRegistry.


        :param aws_key: The aws_key of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """
        if aws_key is None:
            raise ValueError("Invalid value for `aws_key`, must not be `None`")  # noqa: E501

        self._aws_key = aws_key

    @property
    def aws_secret(self):
        """Gets the aws_secret of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The aws_secret of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._aws_secret

    @aws_secret.setter
    def aws_secret(self, aws_secret):
        """Sets the aws_secret of this ComCapillaryOpsDeployerBoECRRegistry.


        :param aws_secret: The aws_secret of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """
        if aws_secret is None:
            raise ValueError("Invalid value for `aws_secret`, must not be `None`")  # noqa: E501

        self._aws_secret = aws_secret

    @property
    def aws_region(self):
        """Gets the aws_region of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The aws_region of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._aws_region

    @aws_region.setter
    def aws_region(self, aws_region):
        """Sets the aws_region of this ComCapillaryOpsDeployerBoECRRegistry.


        :param aws_region: The aws_region of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """
        if aws_region is None:
            raise ValueError("Invalid value for `aws_region`, must not be `None`")  # noqa: E501

        self._aws_region = aws_region

    @property
    def aws_account_id(self):
        """Gets the aws_account_id of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501


        :return: The aws_account_id of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :rtype: str
        """
        return self._aws_account_id

    @aws_account_id.setter
    def aws_account_id(self, aws_account_id):
        """Sets the aws_account_id of this ComCapillaryOpsDeployerBoECRRegistry.


        :param aws_account_id: The aws_account_id of this ComCapillaryOpsDeployerBoECRRegistry.  # noqa: E501
        :type: str
        """
        if aws_account_id is None:
            raise ValueError("Invalid value for `aws_account_id`, must not be `None`")  # noqa: E501

        self._aws_account_id = aws_account_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoECRRegistry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoECRRegistry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
