# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'int',
        'state': 'str',
        'description': 'str',
        'updated_on': 'str',
        'links': 'ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRLinks',
        'source': 'ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef',
        'destination': 'ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'state': 'state',
        'description': 'description',
        'updated_on': 'updated_on',
        'links': 'links',
        'source': 'source',
        'destination': 'destination'
    }

    def __init__(self, type=None, id=None, state=None, description=None, updated_on=None, links=None, source=None, destination=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._id = None
        self._state = None
        self._description = None
        self._updated_on = None
        self._links = None
        self._source = None
        self._destination = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if id is not None:
            self.id = id
        if state is not None:
            self.state = state
        if description is not None:
            self.description = description
        if updated_on is not None:
            self.updated_on = updated_on
        if links is not None:
            self.links = links
        if source is not None:
            self.source = source
        if destination is not None:
            self.destination = destination

    @property
    def type(self):
        """Gets the type of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The type of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param type: The type of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The id of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param id: The id of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def state(self):
        """Gets the state of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The state of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param state: The state of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def description(self):
        """Gets the description of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The description of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param description: The description of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def updated_on(self):
        """Gets the updated_on of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The updated_on of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: str
        """
        return self._updated_on

    @updated_on.setter
    def updated_on(self, updated_on):
        """Sets the updated_on of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param updated_on: The updated_on of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: str
        """

        self._updated_on = updated_on

    @property
    def links(self):
        """Gets the links of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The links of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param links: The links of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRLinks
        """

        self._links = links

    @property
    def source(self):
        """Gets the source of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The source of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param source: The source of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef
        """

        self._source = source

    @property
    def destination(self):
        """Gets the destination of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501


        :return: The destination of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :rtype: ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.


        :param destination: The destination of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField.  # noqa: E501
        :type: ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef
        """

        self._destination = destination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRField):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
