# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsCpBoAlertManagerPayloadAlert(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'labels': 'dict(str, str)',
        'annotations': 'dict(str, str)',
        'starts_at': 'str',
        'ends_at': 'str',
        'generator_url': 'str',
        'fingerprint': 'str',
        'severity': 'str',
        'message': 'str',
        'resource_name': 'str',
        'namespace': 'str',
        'resource_type': 'str',
        'pod': 'str'
    }

    attribute_map = {
        'status': 'status',
        'labels': 'labels',
        'annotations': 'annotations',
        'starts_at': 'startsAt',
        'ends_at': 'endsAt',
        'generator_url': 'generatorURL',
        'fingerprint': 'fingerprint',
        'severity': 'severity',
        'message': 'message',
        'resource_name': 'resourceName',
        'namespace': 'namespace',
        'resource_type': 'resourceType',
        'pod': 'pod'
    }

    def __init__(self, status=None, labels=None, annotations=None, starts_at=None, ends_at=None, generator_url=None, fingerprint=None, severity=None, message=None, resource_name=None, namespace=None, resource_type=None, pod=None):  # noqa: E501
        """ComCapillaryOpsCpBoAlertManagerPayloadAlert - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._labels = None
        self._annotations = None
        self._starts_at = None
        self._ends_at = None
        self._generator_url = None
        self._fingerprint = None
        self._severity = None
        self._message = None
        self._resource_name = None
        self._namespace = None
        self._resource_type = None
        self._pod = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if labels is not None:
            self.labels = labels
        if annotations is not None:
            self.annotations = annotations
        if starts_at is not None:
            self.starts_at = starts_at
        if ends_at is not None:
            self.ends_at = ends_at
        if generator_url is not None:
            self.generator_url = generator_url
        if fingerprint is not None:
            self.fingerprint = fingerprint
        if severity is not None:
            self.severity = severity
        if message is not None:
            self.message = message
        if resource_name is not None:
            self.resource_name = resource_name
        if namespace is not None:
            self.namespace = namespace
        if resource_type is not None:
            self.resource_type = resource_type
        if pod is not None:
            self.pod = pod

    @property
    def status(self):
        """Gets the status of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The status of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param status: The status of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def labels(self):
        """Gets the labels of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The labels of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._labels

    @labels.setter
    def labels(self, labels):
        """Sets the labels of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param labels: The labels of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: dict(str, str)
        """

        self._labels = labels

    @property
    def annotations(self):
        """Gets the annotations of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The annotations of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations):
        """Sets the annotations of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param annotations: The annotations of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: dict(str, str)
        """

        self._annotations = annotations

    @property
    def starts_at(self):
        """Gets the starts_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The starts_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._starts_at

    @starts_at.setter
    def starts_at(self, starts_at):
        """Sets the starts_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param starts_at: The starts_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._starts_at = starts_at

    @property
    def ends_at(self):
        """Gets the ends_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The ends_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._ends_at

    @ends_at.setter
    def ends_at(self, ends_at):
        """Sets the ends_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param ends_at: The ends_at of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._ends_at = ends_at

    @property
    def generator_url(self):
        """Gets the generator_url of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The generator_url of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._generator_url

    @generator_url.setter
    def generator_url(self, generator_url):
        """Sets the generator_url of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param generator_url: The generator_url of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._generator_url = generator_url

    @property
    def fingerprint(self):
        """Gets the fingerprint of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The fingerprint of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._fingerprint

    @fingerprint.setter
    def fingerprint(self, fingerprint):
        """Sets the fingerprint of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param fingerprint: The fingerprint of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._fingerprint = fingerprint

    @property
    def severity(self):
        """Gets the severity of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The severity of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._severity

    @severity.setter
    def severity(self, severity):
        """Sets the severity of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param severity: The severity of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._severity = severity

    @property
    def message(self):
        """Gets the message of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The message of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param message: The message of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def resource_name(self):
        """Gets the resource_name of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The resource_name of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._resource_name

    @resource_name.setter
    def resource_name(self, resource_name):
        """Sets the resource_name of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param resource_name: The resource_name of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._resource_name = resource_name

    @property
    def namespace(self):
        """Gets the namespace of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The namespace of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param namespace: The namespace of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def resource_type(self):
        """Gets the resource_type of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The resource_type of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._resource_type

    @resource_type.setter
    def resource_type(self, resource_type):
        """Sets the resource_type of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param resource_type: The resource_type of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._resource_type = resource_type

    @property
    def pod(self):
        """Gets the pod of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501


        :return: The pod of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :rtype: str
        """
        return self._pod

    @pod.setter
    def pod(self, pod):
        """Sets the pod of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.


        :param pod: The pod of this ComCapillaryOpsCpBoAlertManagerPayloadAlert.  # noqa: E501
        :type: str
        """

        self._pod = pod

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsCpBoAlertManagerPayloadAlert, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsCpBoAlertManagerPayloadAlert):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
