# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'protocol': 'str',
        'endpoint': 'str'
    }

    attribute_map = {
        'protocol': 'protocol',
        'endpoint': 'endpoint'
    }

    def __init__(self, protocol=None, endpoint=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint - a model defined in Swagger"""  # noqa: E501
        self._protocol = None
        self._endpoint = None
        self.discriminator = None
        if protocol is not None:
            self.protocol = protocol
        if endpoint is not None:
            self.endpoint = endpoint

    @property
    def protocol(self):
        """Gets the protocol of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.  # noqa: E501


        :return: The protocol of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.


        :param protocol: The protocol of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.  # noqa: E501
        :type: str
        """

        self._protocol = protocol

    @property
    def endpoint(self):
        """Gets the endpoint of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.  # noqa: E501


        :return: The endpoint of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.


        :param endpoint: The endpoint of this ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint.  # noqa: E501
        :type: str
        """

        self._endpoint = endpoint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoApplicationServiceDetailsEndpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
