# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsCpBoQASuite(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'run_id': 'str',
        'module': 'str',
        'deployment_id': 'str',
        'environment_variables': 'dict(str, str)'
    }

    attribute_map = {
        'run_id': 'runId',
        'module': 'module',
        'deployment_id': 'deploymentId',
        'environment_variables': 'environmentVariables'
    }

    def __init__(self, run_id=None, module=None, deployment_id=None, environment_variables=None):  # noqa: E501
        """ComCapillaryOpsCpBoQASuite - a model defined in Swagger"""  # noqa: E501
        self._run_id = None
        self._module = None
        self._deployment_id = None
        self._environment_variables = None
        self.discriminator = None
        if run_id is not None:
            self.run_id = run_id
        self.module = module
        if deployment_id is not None:
            self.deployment_id = deployment_id
        if environment_variables is not None:
            self.environment_variables = environment_variables

    @property
    def run_id(self):
        """Gets the run_id of this ComCapillaryOpsCpBoQASuite.  # noqa: E501


        :return: The run_id of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :rtype: str
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this ComCapillaryOpsCpBoQASuite.


        :param run_id: The run_id of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :type: str
        """

        self._run_id = run_id

    @property
    def module(self):
        """Gets the module of this ComCapillaryOpsCpBoQASuite.  # noqa: E501


        :return: The module of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :rtype: str
        """
        return self._module

    @module.setter
    def module(self, module):
        """Sets the module of this ComCapillaryOpsCpBoQASuite.


        :param module: The module of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :type: str
        """
        if module is None:
            raise ValueError("Invalid value for `module`, must not be `None`")  # noqa: E501

        self._module = module

    @property
    def deployment_id(self):
        """Gets the deployment_id of this ComCapillaryOpsCpBoQASuite.  # noqa: E501


        :return: The deployment_id of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :rtype: str
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id):
        """Sets the deployment_id of this ComCapillaryOpsCpBoQASuite.


        :param deployment_id: The deployment_id of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :type: str
        """

        self._deployment_id = deployment_id

    @property
    def environment_variables(self):
        """Gets the environment_variables of this ComCapillaryOpsCpBoQASuite.  # noqa: E501


        :return: The environment_variables of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._environment_variables

    @environment_variables.setter
    def environment_variables(self, environment_variables):
        """Sets the environment_variables of this ComCapillaryOpsCpBoQASuite.


        :param environment_variables: The environment_variables of this ComCapillaryOpsCpBoQASuite.  # noqa: E501
        :type: dict(str, str)
        """

        self._environment_variables = environment_variables

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsCpBoQASuite, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsCpBoQASuite):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
