# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoBuild(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'code_build_id': 'str',
        'application_id': 'str',
        'application_family': 'str',
        'tag': 'str',
        'status': 'str',
        'environment_variables': 'dict(str, str)',
        'timestamp': 'int',
        'image': 'str',
        'triggered_by': 'str',
        'description': 'str',
        'promoted': 'bool',
        'unpromoted': 'bool',
        'promotion_intent': 'str',
        'promotable': 'bool',
        'artifact_url': 'str',
        'test_build': 'bool',
        'additional_repository_images': 'list[str]'
    }

    attribute_map = {
        'id': 'id',
        'code_build_id': 'codeBuildId',
        'application_id': 'applicationId',
        'application_family': 'applicationFamily',
        'tag': 'tag',
        'status': 'status',
        'environment_variables': 'environmentVariables',
        'timestamp': 'timestamp',
        'image': 'image',
        'triggered_by': 'triggeredBy',
        'description': 'description',
        'promoted': 'promoted',
        'unpromoted': 'unpromoted',
        'promotion_intent': 'promotionIntent',
        'promotable': 'promotable',
        'artifact_url': 'artifactUrl',
        'test_build': 'testBuild',
        'additional_repository_images': 'additionalRepositoryImages'
    }

    def __init__(self, id=None, code_build_id=None, application_id=None, application_family=None, tag=None, status=None, environment_variables=None, timestamp=None, image=None, triggered_by=None, description=None, promoted=None, unpromoted=None, promotion_intent=None, promotable=None, artifact_url=None, test_build=None, additional_repository_images=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoBuild - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._code_build_id = None
        self._application_id = None
        self._application_family = None
        self._tag = None
        self._status = None
        self._environment_variables = None
        self._timestamp = None
        self._image = None
        self._triggered_by = None
        self._description = None
        self._promoted = None
        self._unpromoted = None
        self._promotion_intent = None
        self._promotable = None
        self._artifact_url = None
        self._test_build = None
        self._additional_repository_images = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if code_build_id is not None:
            self.code_build_id = code_build_id
        self.application_id = application_id
        if application_family is not None:
            self.application_family = application_family
        self.tag = tag
        if status is not None:
            self.status = status
        if environment_variables is not None:
            self.environment_variables = environment_variables
        if timestamp is not None:
            self.timestamp = timestamp
        if image is not None:
            self.image = image
        if triggered_by is not None:
            self.triggered_by = triggered_by
        if description is not None:
            self.description = description
        if promoted is not None:
            self.promoted = promoted
        if unpromoted is not None:
            self.unpromoted = unpromoted
        if promotion_intent is not None:
            self.promotion_intent = promotion_intent
        if promotable is not None:
            self.promotable = promotable
        if artifact_url is not None:
            self.artifact_url = artifact_url
        if test_build is not None:
            self.test_build = test_build
        if additional_repository_images is not None:
            self.additional_repository_images = additional_repository_images

    @property
    def id(self):
        """Gets the id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ComCapillaryOpsDeployerBoBuild.


        :param id: The id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def code_build_id(self):
        """Gets the code_build_id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The code_build_id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._code_build_id

    @code_build_id.setter
    def code_build_id(self, code_build_id):
        """Sets the code_build_id of this ComCapillaryOpsDeployerBoBuild.


        :param code_build_id: The code_build_id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """

        self._code_build_id = code_build_id

    @property
    def application_id(self):
        """Gets the application_id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The application_id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this ComCapillaryOpsDeployerBoBuild.


        :param application_id: The application_id of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """
        if application_id is None:
            raise ValueError("Invalid value for `application_id`, must not be `None`")  # noqa: E501

        self._application_id = application_id

    @property
    def application_family(self):
        """Gets the application_family of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The application_family of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._application_family

    @application_family.setter
    def application_family(self, application_family):
        """Sets the application_family of this ComCapillaryOpsDeployerBoBuild.


        :param application_family: The application_family of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """
        allowed_values = ["CRM", "ECOMMERCE", "INTEGRATIONS", "OPS"]  # noqa: E501
        if application_family not in allowed_values:
            raise ValueError(
                "Invalid value for `application_family` ({0}), must be one of {1}"  # noqa: E501
                .format(application_family, allowed_values)
            )

        self._application_family = application_family

    @property
    def tag(self):
        """Gets the tag of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The tag of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ComCapillaryOpsDeployerBoBuild.


        :param tag: The tag of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """
        if tag is None:
            raise ValueError("Invalid value for `tag`, must not be `None`")  # noqa: E501

        self._tag = tag

    @property
    def status(self):
        """Gets the status of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The status of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ComCapillaryOpsDeployerBoBuild.


        :param status: The status of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """
        allowed_values = ["SUCCEEDED", "FAILED", "FAULT", "TIMED_OUT", "IN_PROGRESS", "STOPPED", "null"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def environment_variables(self):
        """Gets the environment_variables of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The environment_variables of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._environment_variables

    @environment_variables.setter
    def environment_variables(self, environment_variables):
        """Sets the environment_variables of this ComCapillaryOpsDeployerBoBuild.


        :param environment_variables: The environment_variables of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: dict(str, str)
        """

        self._environment_variables = environment_variables

    @property
    def timestamp(self):
        """Gets the timestamp of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The timestamp of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ComCapillaryOpsDeployerBoBuild.


        :param timestamp: The timestamp of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def image(self):
        """Gets the image of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The image of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this ComCapillaryOpsDeployerBoBuild.


        :param image: The image of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """

        self._image = image

    @property
    def triggered_by(self):
        """Gets the triggered_by of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The triggered_by of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._triggered_by

    @triggered_by.setter
    def triggered_by(self, triggered_by):
        """Sets the triggered_by of this ComCapillaryOpsDeployerBoBuild.


        :param triggered_by: The triggered_by of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """

        self._triggered_by = triggered_by

    @property
    def description(self):
        """Gets the description of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The description of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ComCapillaryOpsDeployerBoBuild.


        :param description: The description of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def promoted(self):
        """Gets the promoted of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The promoted of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: bool
        """
        return self._promoted

    @promoted.setter
    def promoted(self, promoted):
        """Sets the promoted of this ComCapillaryOpsDeployerBoBuild.


        :param promoted: The promoted of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: bool
        """

        self._promoted = promoted

    @property
    def unpromoted(self):
        """Gets the unpromoted of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The unpromoted of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: bool
        """
        return self._unpromoted

    @unpromoted.setter
    def unpromoted(self, unpromoted):
        """Sets the unpromoted of this ComCapillaryOpsDeployerBoBuild.


        :param unpromoted: The unpromoted of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: bool
        """

        self._unpromoted = unpromoted

    @property
    def promotion_intent(self):
        """Gets the promotion_intent of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The promotion_intent of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._promotion_intent

    @promotion_intent.setter
    def promotion_intent(self, promotion_intent):
        """Sets the promotion_intent of this ComCapillaryOpsDeployerBoBuild.


        :param promotion_intent: The promotion_intent of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """
        allowed_values = ["NA", "NOT_CC_ENABLED", "HOTFIX", "RELEASE"]  # noqa: E501
        if promotion_intent not in allowed_values:
            raise ValueError(
                "Invalid value for `promotion_intent` ({0}), must be one of {1}"  # noqa: E501
                .format(promotion_intent, allowed_values)
            )

        self._promotion_intent = promotion_intent

    @property
    def promotable(self):
        """Gets the promotable of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The promotable of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: bool
        """
        return self._promotable

    @promotable.setter
    def promotable(self, promotable):
        """Sets the promotable of this ComCapillaryOpsDeployerBoBuild.


        :param promotable: The promotable of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: bool
        """

        self._promotable = promotable

    @property
    def artifact_url(self):
        """Gets the artifact_url of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The artifact_url of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: str
        """
        return self._artifact_url

    @artifact_url.setter
    def artifact_url(self, artifact_url):
        """Sets the artifact_url of this ComCapillaryOpsDeployerBoBuild.


        :param artifact_url: The artifact_url of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: str
        """

        self._artifact_url = artifact_url

    @property
    def test_build(self):
        """Gets the test_build of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The test_build of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: bool
        """
        return self._test_build

    @test_build.setter
    def test_build(self, test_build):
        """Sets the test_build of this ComCapillaryOpsDeployerBoBuild.


        :param test_build: The test_build of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: bool
        """

        self._test_build = test_build

    @property
    def additional_repository_images(self):
        """Gets the additional_repository_images of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501


        :return: The additional_repository_images of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :rtype: list[str]
        """
        return self._additional_repository_images

    @additional_repository_images.setter
    def additional_repository_images(self, additional_repository_images):
        """Sets the additional_repository_images of this ComCapillaryOpsDeployerBoBuild.


        :param additional_repository_images: The additional_repository_images of this ComCapillaryOpsDeployerBoBuild.  # noqa: E501
        :type: list[str]
        """

        self._additional_repository_images = additional_repository_images

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoBuild, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoBuild):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
