# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sha': 'str',
        'branch_name': 'str',
        'commit': 'dict(str, object)',
        'branch': 'dict(str, str)'
    }

    attribute_map = {
        'sha': 'sha',
        'branch_name': 'branchName',
        'commit': 'commit',
        'branch': 'branch'
    }

    def __init__(self, sha=None, branch_name=None, commit=None, branch=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef - a model defined in Swagger"""  # noqa: E501
        self._sha = None
        self._branch_name = None
        self._commit = None
        self._branch = None
        self.discriminator = None
        if sha is not None:
            self.sha = sha
        if branch_name is not None:
            self.branch_name = branch_name
        if commit is not None:
            self.commit = commit
        if branch is not None:
            self.branch = branch

    @property
    def sha(self):
        """Gets the sha of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501


        :return: The sha of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :rtype: str
        """
        return self._sha

    @sha.setter
    def sha(self, sha):
        """Sets the sha of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.


        :param sha: The sha of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :type: str
        """

        self._sha = sha

    @property
    def branch_name(self):
        """Gets the branch_name of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501


        :return: The branch_name of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :rtype: str
        """
        return self._branch_name

    @branch_name.setter
    def branch_name(self, branch_name):
        """Sets the branch_name of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.


        :param branch_name: The branch_name of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :type: str
        """

        self._branch_name = branch_name

    @property
    def commit(self):
        """Gets the commit of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501


        :return: The commit of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._commit

    @commit.setter
    def commit(self, commit):
        """Sets the commit of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.


        :param commit: The commit of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :type: dict(str, object)
        """

        self._commit = commit

    @property
    def branch(self):
        """Gets the branch of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501


        :return: The branch of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """Sets the branch of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.


        :param branch: The branch of this ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef.  # noqa: E501
        :type: dict(str, str)
        """

        self._branch = branch

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoWebhookBitbucketBitbucketPRBranchRef):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
