# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ComCapillaryOpsDeployerBoWebhookSonarCondition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metric': 'str',
        'operator': 'str',
        'value': 'str',
        'status': 'str',
        'error_threshold': 'str',
        'metric_label': 'str'
    }

    attribute_map = {
        'metric': 'metric',
        'operator': 'operator',
        'value': 'value',
        'status': 'status',
        'error_threshold': 'errorThreshold',
        'metric_label': 'metricLabel'
    }

    def __init__(self, metric=None, operator=None, value=None, status=None, error_threshold=None, metric_label=None):  # noqa: E501
        """ComCapillaryOpsDeployerBoWebhookSonarCondition - a model defined in Swagger"""  # noqa: E501
        self._metric = None
        self._operator = None
        self._value = None
        self._status = None
        self._error_threshold = None
        self._metric_label = None
        self.discriminator = None
        if metric is not None:
            self.metric = metric
        if operator is not None:
            self.operator = operator
        if value is not None:
            self.value = value
        if status is not None:
            self.status = status
        if error_threshold is not None:
            self.error_threshold = error_threshold
        if metric_label is not None:
            self.metric_label = metric_label

    @property
    def metric(self):
        """Gets the metric of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501


        :return: The metric of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :rtype: str
        """
        return self._metric

    @metric.setter
    def metric(self, metric):
        """Sets the metric of this ComCapillaryOpsDeployerBoWebhookSonarCondition.


        :param metric: The metric of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :type: str
        """

        self._metric = metric

    @property
    def operator(self):
        """Gets the operator of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501


        :return: The operator of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :rtype: str
        """
        return self._operator

    @operator.setter
    def operator(self, operator):
        """Sets the operator of this ComCapillaryOpsDeployerBoWebhookSonarCondition.


        :param operator: The operator of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :type: str
        """

        self._operator = operator

    @property
    def value(self):
        """Gets the value of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501


        :return: The value of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ComCapillaryOpsDeployerBoWebhookSonarCondition.


        :param value: The value of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def status(self):
        """Gets the status of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501


        :return: The status of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ComCapillaryOpsDeployerBoWebhookSonarCondition.


        :param status: The status of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def error_threshold(self):
        """Gets the error_threshold of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501


        :return: The error_threshold of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :rtype: str
        """
        return self._error_threshold

    @error_threshold.setter
    def error_threshold(self, error_threshold):
        """Sets the error_threshold of this ComCapillaryOpsDeployerBoWebhookSonarCondition.


        :param error_threshold: The error_threshold of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :type: str
        """

        self._error_threshold = error_threshold

    @property
    def metric_label(self):
        """Gets the metric_label of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501


        :return: The metric_label of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :rtype: str
        """
        return self._metric_label

    @metric_label.setter
    def metric_label(self, metric_label):
        """Sets the metric_label of this ComCapillaryOpsDeployerBoWebhookSonarCondition.


        :param metric_label: The metric_label of this ComCapillaryOpsDeployerBoWebhookSonarCondition.  # noqa: E501
        :type: str
        """

        self._metric_label = metric_label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ComCapillaryOpsDeployerBoWebhookSonarCondition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCapillaryOpsDeployerBoWebhookSonarCondition):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
