# coding: utf-8

"""
    Api Documentation

    Api Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class UiArtifactoryControllerApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def associate_stacks_using_post(self, artifactory_id, stacks, **kwargs):  # noqa: E501
        """associateStacks  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.associate_stacks_using_post(artifactory_id, stacks, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param list[str] stacks: stacks (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.associate_stacks_using_post_with_http_info(artifactory_id, stacks, **kwargs)  # noqa: E501
        else:
            (data) = self.associate_stacks_using_post_with_http_info(artifactory_id, stacks, **kwargs)  # noqa: E501
            return data

    def associate_stacks_using_post_with_http_info(self, artifactory_id, stacks, **kwargs):  # noqa: E501
        """associateStacks  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.associate_stacks_using_post_with_http_info(artifactory_id, stacks, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param list[str] stacks: stacks (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id', 'stacks']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method associate_stacks_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `associate_stacks_using_post`")  # noqa: E501
        # verify the required parameter 'stacks' is set
        if self.api_client.client_side_validation and ('stacks' not in params or
                                                       params['stacks'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `stacks` when calling `associate_stacks_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'stacks' in params:
            body_params = params['stacks']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/{artifactoryId}/associate-projects', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_artifactory_mirror_using_post(self, artifactory_mirror, **kwargs):  # noqa: E501
        """createArtifactoryMirror  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_artifactory_mirror_using_post(artifactory_mirror, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ArtifactoryMirror artifactory_mirror: artifactoryMirror (required)
        :return: ArtifactoryMirror
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_artifactory_mirror_using_post_with_http_info(artifactory_mirror, **kwargs)  # noqa: E501
        else:
            (data) = self.create_artifactory_mirror_using_post_with_http_info(artifactory_mirror, **kwargs)  # noqa: E501
            return data

    def create_artifactory_mirror_using_post_with_http_info(self, artifactory_mirror, **kwargs):  # noqa: E501
        """createArtifactoryMirror  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_artifactory_mirror_using_post_with_http_info(artifactory_mirror, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ArtifactoryMirror artifactory_mirror: artifactoryMirror (required)
        :return: ArtifactoryMirror
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_mirror']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_artifactory_mirror_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_mirror' is set
        if self.api_client.client_side_validation and ('artifactory_mirror' not in params or
                                                       params['artifactory_mirror'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_mirror` when calling `create_artifactory_mirror_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'artifactory_mirror' in params:
            body_params = params['artifactory_mirror']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/mirrors', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ArtifactoryMirror',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_basic_docker_artifactory_using_post(self, basic_docker_dto, **kwargs):  # noqa: E501
        """createBasicDockerArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_basic_docker_artifactory_using_post(basic_docker_dto, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BasicDockerDTO basic_docker_dto: basicDockerDTO (required)
        :return: BasicDockerArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_basic_docker_artifactory_using_post_with_http_info(basic_docker_dto, **kwargs)  # noqa: E501
        else:
            (data) = self.create_basic_docker_artifactory_using_post_with_http_info(basic_docker_dto, **kwargs)  # noqa: E501
            return data

    def create_basic_docker_artifactory_using_post_with_http_info(self, basic_docker_dto, **kwargs):  # noqa: E501
        """createBasicDockerArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_basic_docker_artifactory_using_post_with_http_info(basic_docker_dto, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param BasicDockerDTO basic_docker_dto: basicDockerDTO (required)
        :return: BasicDockerArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['basic_docker_dto']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_basic_docker_artifactory_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'basic_docker_dto' is set
        if self.api_client.client_side_validation and ('basic_docker_dto' not in params or
                                                       params['basic_docker_dto'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `basic_docker_dto` when calling `create_basic_docker_artifactory_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'basic_docker_dto' in params:
            body_params = params['basic_docker_dto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/others', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BasicDockerArtifactory',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_ecr_artifactory_using_post1(self, ecr_artifactory, **kwargs):  # noqa: E501
        """createECRArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_ecr_artifactory_using_post1(ecr_artifactory, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ECRArtifactory ecr_artifactory: ecrArtifactory (required)
        :return: ECRArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_ecr_artifactory_using_post1_with_http_info(ecr_artifactory, **kwargs)  # noqa: E501
        else:
            (data) = self.create_ecr_artifactory_using_post1_with_http_info(ecr_artifactory, **kwargs)  # noqa: E501
            return data

    def create_ecr_artifactory_using_post1_with_http_info(self, ecr_artifactory, **kwargs):  # noqa: E501
        """createECRArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_ecr_artifactory_using_post1_with_http_info(ecr_artifactory, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ECRArtifactory ecr_artifactory: ecrArtifactory (required)
        :return: ECRArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['ecr_artifactory']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_ecr_artifactory_using_post1" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'ecr_artifactory' is set
        if self.api_client.client_side_validation and ('ecr_artifactory' not in params or
                                                       params['ecr_artifactory'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ecr_artifactory` when calling `create_ecr_artifactory_using_post1`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ecr_artifactory' in params:
            body_params = params['ecr_artifactory']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ECRArtifactory',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_artifactory_using_delete(self, artifactory_id, **kwargs):  # noqa: E501
        """deleteArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_artifactory_using_delete(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_artifactory_using_delete_with_http_info(artifactory_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_artifactory_using_delete_with_http_info(artifactory_id, **kwargs)  # noqa: E501
            return data

    def delete_artifactory_using_delete_with_http_info(self, artifactory_id, **kwargs):  # noqa: E501
        """deleteArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_artifactory_using_delete_with_http_info(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_artifactory_using_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `delete_artifactory_using_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/v2/{artifactoryId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_ecr_artifactory_using_delete(self, artifactory_id, **kwargs):  # noqa: E501
        """deleteECRArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_ecr_artifactory_using_delete(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: bool
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_ecr_artifactory_using_delete_with_http_info(artifactory_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_ecr_artifactory_using_delete_with_http_info(artifactory_id, **kwargs)  # noqa: E501
            return data

    def delete_ecr_artifactory_using_delete_with_http_info(self, artifactory_id, **kwargs):  # noqa: E501
        """deleteECRArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_ecr_artifactory_using_delete_with_http_info(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: bool
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_ecr_artifactory_using_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `delete_ecr_artifactory_using_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/{artifactoryId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='bool',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_artifactories_for_stack_using_get(self, stack_name, **kwargs):  # noqa: E501
        """getAllArtifactoriesForStack  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_artifactories_for_stack_using_get(stack_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str stack_name: stackName (required)
        :return: list[Artifactory]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_artifactories_for_stack_using_get_with_http_info(stack_name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_all_artifactories_for_stack_using_get_with_http_info(stack_name, **kwargs)  # noqa: E501
            return data

    def get_all_artifactories_for_stack_using_get_with_http_info(self, stack_name, **kwargs):  # noqa: E501
        """getAllArtifactoriesForStack  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_artifactories_for_stack_using_get_with_http_info(stack_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str stack_name: stackName (required)
        :return: list[Artifactory]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['stack_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_artifactories_for_stack_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'stack_name' is set
        if self.api_client.client_side_validation and ('stack_name' not in params or
                                                       params['stack_name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `stack_name` when calling `get_all_artifactories_for_stack_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'stack_name' in params:
            path_params['stackName'] = params['stack_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/stack/{stackName}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Artifactory]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_artifactories_using_get1(self, **kwargs):  # noqa: E501
        """getAllArtifactories  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_artifactories_using_get1(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Artifactory]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_artifactories_using_get1_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_artifactories_using_get1_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_artifactories_using_get1_with_http_info(self, **kwargs):  # noqa: E501
        """getAllArtifactories  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_artifactories_using_get1_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[Artifactory]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_artifactories_using_get1" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Artifactory]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_artifactory_by_id_using_get(self, artifactory_id, **kwargs):  # noqa: E501
        """getArtifactoryById  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_artifactory_by_id_using_get(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: Artifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_artifactory_by_id_using_get_with_http_info(artifactory_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_artifactory_by_id_using_get_with_http_info(artifactory_id, **kwargs)  # noqa: E501
            return data

    def get_artifactory_by_id_using_get_with_http_info(self, artifactory_id, **kwargs):  # noqa: E501
        """getArtifactoryById  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_artifactory_by_id_using_get_with_http_info(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: Artifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_artifactory_by_id_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `get_artifactory_by_id_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/{artifactoryId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Artifactory',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_artifactory_by_name_using_get(self, name, **kwargs):  # noqa: E501
        """getArtifactoryByName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_artifactory_by_name_using_get(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: name (required)
        :return: Artifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_artifactory_by_name_using_get_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_artifactory_by_name_using_get_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get_artifactory_by_name_using_get_with_http_info(self, name, **kwargs):  # noqa: E501
        """getArtifactoryByName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_artifactory_by_name_using_get_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: name (required)
        :return: Artifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_artifactory_by_name_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if self.api_client.client_side_validation and ('name' not in params or
                                                       params['name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `name` when calling `get_artifactory_by_name_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/name/{name}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Artifactory',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_repositories_by_artifactory_name_using_get(self, name, **kwargs):  # noqa: E501
        """getRepositoriesByArtifactoryName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_repositories_by_artifactory_name_using_get(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: name (required)
        :param str artifact_type: artifactType
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_repositories_by_artifactory_name_using_get_with_http_info(name, **kwargs)  # noqa: E501
        else:
            (data) = self.get_repositories_by_artifactory_name_using_get_with_http_info(name, **kwargs)  # noqa: E501
            return data

    def get_repositories_by_artifactory_name_using_get_with_http_info(self, name, **kwargs):  # noqa: E501
        """getRepositoriesByArtifactoryName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_repositories_by_artifactory_name_using_get_with_http_info(name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: name (required)
        :param str artifact_type: artifactType
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'artifact_type']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_repositories_by_artifactory_name_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if self.api_client.client_side_validation and ('name' not in params or
                                                       params['name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `name` when calling `get_repositories_by_artifactory_name_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []
        if 'artifact_type' in params:
            query_params.append(('artifactType', params['artifact_type']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/name/{name}/repos', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_repositories_using_get(self, artifactory_id, **kwargs):  # noqa: E501
        """getRepositories  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_repositories_using_get(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_repositories_using_get_with_http_info(artifactory_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_repositories_using_get_with_http_info(artifactory_id, **kwargs)  # noqa: E501
            return data

    def get_repositories_using_get_with_http_info(self, artifactory_id, **kwargs):  # noqa: E501
        """getRepositories  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_repositories_using_get_with_http_info(artifactory_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_repositories_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `get_repositories_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/{artifactoryId}/repos', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tags_by_artifactory_name_using_get(self, name, repo, **kwargs):  # noqa: E501
        """getTagsByArtifactoryName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_by_artifactory_name_using_get(name, repo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: name (required)
        :param str repo: repo (required)
        :param str artifact_type: artifactType
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tags_by_artifactory_name_using_get_with_http_info(name, repo, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tags_by_artifactory_name_using_get_with_http_info(name, repo, **kwargs)  # noqa: E501
            return data

    def get_tags_by_artifactory_name_using_get_with_http_info(self, name, repo, **kwargs):  # noqa: E501
        """getTagsByArtifactoryName  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_by_artifactory_name_using_get_with_http_info(name, repo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: name (required)
        :param str repo: repo (required)
        :param str artifact_type: artifactType
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'repo', 'artifact_type']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tags_by_artifactory_name_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'name' is set
        if self.api_client.client_side_validation and ('name' not in params or
                                                       params['name'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `name` when calling `get_tags_by_artifactory_name_using_get`")  # noqa: E501
        # verify the required parameter 'repo' is set
        if self.api_client.client_side_validation and ('repo' not in params or
                                                       params['repo'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo` when calling `get_tags_by_artifactory_name_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'name' in params:
            path_params['name'] = params['name']  # noqa: E501

        query_params = []
        if 'artifact_type' in params:
            query_params.append(('artifactType', params['artifact_type']))  # noqa: E501
        if 'repo' in params:
            query_params.append(('repo', params['repo']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/name/{name}/tags', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tags_using_get(self, artifactory_id, repo, **kwargs):  # noqa: E501
        """getTags  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_using_get(artifactory_id, repo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param str repo: repo (required)
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tags_using_get_with_http_info(artifactory_id, repo, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tags_using_get_with_http_info(artifactory_id, repo, **kwargs)  # noqa: E501
            return data

    def get_tags_using_get_with_http_info(self, artifactory_id, repo, **kwargs):  # noqa: E501
        """getTags  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tags_using_get_with_http_info(artifactory_id, repo, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param str repo: repo (required)
        :return: list[str]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id', 'repo']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tags_using_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `get_tags_using_get`")  # noqa: E501
        # verify the required parameter 'repo' is set
        if self.api_client.client_side_validation and ('repo' not in params or
                                                       params['repo'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `repo` when calling `get_tags_using_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []
        if 'repo' in params:
            query_params.append(('repo', params['repo']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/{artifactoryId}/tags', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[str]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def request_artifactory_linking_using_post(self, artifactory_linking_request, **kwargs):  # noqa: E501
        """requestArtifactoryLinking  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.request_artifactory_linking_using_post(artifactory_linking_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ArtifactoryLinkingRequest artifactory_linking_request: artifactoryLinkingRequest (required)
        :return: OneTimeWebhook
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.request_artifactory_linking_using_post_with_http_info(artifactory_linking_request, **kwargs)  # noqa: E501
        else:
            (data) = self.request_artifactory_linking_using_post_with_http_info(artifactory_linking_request, **kwargs)  # noqa: E501
            return data

    def request_artifactory_linking_using_post_with_http_info(self, artifactory_linking_request, **kwargs):  # noqa: E501
        """requestArtifactoryLinking  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.request_artifactory_linking_using_post_with_http_info(artifactory_linking_request, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ArtifactoryLinkingRequest artifactory_linking_request: artifactoryLinkingRequest (required)
        :return: OneTimeWebhook
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_linking_request']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method request_artifactory_linking_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_linking_request' is set
        if self.api_client.client_side_validation and ('artifactory_linking_request' not in params or
                                                       params['artifactory_linking_request'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_linking_request` when calling `request_artifactory_linking_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'artifactory_linking_request' in params:
            body_params = params['artifactory_linking_request']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/link-container-registry', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='OneTimeWebhook',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_basic_docker_artifactory_using_post(self, artifactory_id, basic_docker_dto, **kwargs):  # noqa: E501
        """updateBasicDockerArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_basic_docker_artifactory_using_post(artifactory_id, basic_docker_dto, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param BasicDockerDTO basic_docker_dto: basicDockerDTO (required)
        :return: BasicDockerArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_basic_docker_artifactory_using_post_with_http_info(artifactory_id, basic_docker_dto, **kwargs)  # noqa: E501
        else:
            (data) = self.update_basic_docker_artifactory_using_post_with_http_info(artifactory_id, basic_docker_dto, **kwargs)  # noqa: E501
            return data

    def update_basic_docker_artifactory_using_post_with_http_info(self, artifactory_id, basic_docker_dto, **kwargs):  # noqa: E501
        """updateBasicDockerArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_basic_docker_artifactory_using_post_with_http_info(artifactory_id, basic_docker_dto, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param BasicDockerDTO basic_docker_dto: basicDockerDTO (required)
        :return: BasicDockerArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id', 'basic_docker_dto']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_basic_docker_artifactory_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `update_basic_docker_artifactory_using_post`")  # noqa: E501
        # verify the required parameter 'basic_docker_dto' is set
        if self.api_client.client_side_validation and ('basic_docker_dto' not in params or
                                                       params['basic_docker_dto'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `basic_docker_dto` when calling `update_basic_docker_artifactory_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'basic_docker_dto' in params:
            body_params = params['basic_docker_dto']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/others/{artifactoryId}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BasicDockerArtifactory',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_ecr_artifactory_using_post(self, artifactory_id, ecr_artifactory, **kwargs):  # noqa: E501
        """updateECRArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_ecr_artifactory_using_post(artifactory_id, ecr_artifactory, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param ECRArtifactory ecr_artifactory: ecrArtifactory (required)
        :return: ECRArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_ecr_artifactory_using_post_with_http_info(artifactory_id, ecr_artifactory, **kwargs)  # noqa: E501
        else:
            (data) = self.update_ecr_artifactory_using_post_with_http_info(artifactory_id, ecr_artifactory, **kwargs)  # noqa: E501
            return data

    def update_ecr_artifactory_using_post_with_http_info(self, artifactory_id, ecr_artifactory, **kwargs):  # noqa: E501
        """updateECRArtifactory  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_ecr_artifactory_using_post_with_http_info(artifactory_id, ecr_artifactory, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str artifactory_id: artifactoryId (required)
        :param ECRArtifactory ecr_artifactory: ecrArtifactory (required)
        :return: ECRArtifactory
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['artifactory_id', 'ecr_artifactory']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_ecr_artifactory_using_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'artifactory_id' is set
        if self.api_client.client_side_validation and ('artifactory_id' not in params or
                                                       params['artifactory_id'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `artifactory_id` when calling `update_ecr_artifactory_using_post`")  # noqa: E501
        # verify the required parameter 'ecr_artifactory' is set
        if self.api_client.client_side_validation and ('ecr_artifactory' not in params or
                                                       params['ecr_artifactory'] is None):  # noqa: E501
            raise ValueError("Missing the required parameter `ecr_artifactory` when calling `update_ecr_artifactory_using_post`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'artifactory_id' in params:
            path_params['artifactoryId'] = params['artifactory_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'ecr_artifactory' in params:
            body_params = params['ecr_artifactory']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['main']  # noqa: E501

        return self.api_client.call_api(
            '/cc-ui/v1/artifactories/{artifactoryId}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ECRArtifactory',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
