name: Update Python SDK

on:
  workflow_dispatch:
    inputs:
      api_url:
        description: 'API docs URL (defaults to facetsdemo.console.facets.cloud)'
        required: false
        default: 'facetsdemo.console.facets.cloud'
        type: string

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Download swagger-codegen CLI
        run: |
          wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.68/swagger-codegen-cli-3.0.68.jar -O swagger-codegen-cli.jar

      - name: Fetch latest API docs
        run: |
          curl https://${{ inputs.api_url }}/v2/api-docs -o api-docs-raw.json

      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Format JSON
        run: |
          jq . api-docs-raw.json > api-docs-fixed.json

      - name: Generate updated SDK
        run: |
          java -jar swagger-codegen-cli.jar generate -i api-docs-fixed.json -l python -o . -c swagger-config.json

      - name: Remove temporary files
        run: |
          rm api-docs-raw.json api-docs-fixed.json swagger-codegen-cli.jar

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update Python SDK from latest API docs"
          title: "Update Python SDK from latest API docs"
          body: |
            This PR updates the Python SDK with the latest API definitions from:
            https://${{ inputs.api_url }}/v2/api-docs
            
            Changes were automatically generated by the GitHub Actions workflow.
          branch: update-sdk
          branch-suffix: timestamp
          delete-branch: true
          base: master

      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"